#!/usr/bin/env bash

set -euo pipefail

declare label
label="$(basename "${1}")"

export "BUILDKITE_LABEL=${label}"

declare exit_code
set +e
"${1}"
exit_code=$?
set -e

source .buildkite/hooks/post-command
exit "${exit_code}"
