#!/usr/bin/env bash

set -euo pipefail

declare label
label="$(basename "${1}")"

export "BUILDKITE_LABEL=${label}"

source .buildkite/hooks/pre-command

declare exit_code
set +x
"${1}"
exit_code=$?
set -x

source .buildkite/hooks/post-command
exit "${exit_code}"
