#!/usr/bin/env bash

set -euo pipefail

get_access_token() {
	local scratch
	scratch="$(mktemp)"

	echo '=> Fetching Access Token'
	access_token_url="$(buildkite-agent meta-data get teamci.access_token_url)"
	if curl -o "${scratch}" --fail -H 'Accept: application/json' "${access_token_url}"; then
		echo 'INFO: retrieved git access token'
		export "ACCESS_TOKEN=$(jq -re '.token' "${scratch}")"
	else
		echo 'FATAL: Could not fetch clone access token. This is an internal error. You can attempt a retry.'
		echo 'WARN: Skipping this check for now. Contact support if this continues.'
		return 7
	fi
}

sync_code() {
	echo '=> Cloning code'
	local repo head_sha head_branch

	repo="$(buildkite-agent meta-data get teamci.repo.slug)"
	head_sha="$(buildkite-agent meta-data get teamci.head_sha)"
	head_branch="$(buildkite-agent meta-data get teamci.head_branch)"

	if [ -z "${repo}" ] || [ -z "${head_sha}" ] || [ -z "${head_branch}" ]; then
		echo "FATAL: Missing repo/sha/branch metadata" 1>&2
		return 1
	fi

	export CODE_DIR="${TEAMCI_CODE_DIR}/${repo}"
	export TEAMCI_REPO_SLUG="${repo}"
	export TEAMCI_COMMIT="${head_sha}"

	if [ -d "${CODE_DIR}/.git" ]; then
		pushd "${CODE_DIR}" > /dev/null

		git remote set-url origin "https://x-access-token:${ACCESS_TOKEN}@github.com/${repo}.git"
	else
		mkdir -p "${CODE_DIR}"

		git clone -v "https://x-access-token:${ACCESS_TOKEN}@github.com/${repo}.git" "${CODE_DIR}"

		pushd "${CODE_DIR}" > /dev/null
	fi

	if git fetch -v --prune origin "${head_branch}" && git checkout -f "${head_sha}"; then
		git clean -fdx
		echo "INFO: code ${head_branch} @ ${head_sha} ready"
		popd > /dev/null
	else
		echo "WARN: could not sync code. Was the branch deleted upstream? Skipping check."
		return 7
	fi
}

run_check() {
	if [ -z "${TEAMCI_CHECK_IMAGE:-}" ]; then
		echo "FATAL: Internal error. TEAMCI_CHECK_IMAGE missing. Please contact support."
		return 7
	fi

	touch logs/execution.log

	get_access_token
	sync_code

	echo "=> Pulling image" | tee -a logs/execution.log
	docker pull "${TEAMCI_CHECK_IMAGE}"  2>&1 | tee -a logs/execution.log

	local output_format

	output_format="$(docker inspect -f '{{ index .Config.Labels "com.teamci.output" }}' "${TEAMCI_CHECK_IMAGE}")"

	if [ -n "${output_format:-}" ]; then
		buildkite-agent meta-data set "teamci.output.${TEAMCI_CHECK_NAME}" "${output_format}"
	else
		buildkite-agent meta-data set "teamci.output.${TEAMCI_CHECK_NAME}" 'plain'
	fi

	echo "=> Executing check" | tee -a logs/execution.log

	local check_exit_code

	set +e
	docker run --rm \
		-v "${CODE_DIR}:/data/code:ro" \
		-v "${PWD}/logs/tap.log:/data/logs/tap.log" \
		--cpus 1 \
		--memory 512m \
		"${TEAMCI_CHECK_IMAGE}" 2>&1 | tee -a logs/execution.log
	check_exit_code=$?
	set -e

	return "${check_exit_code}"
}

main() {
	mkdir -p logs

	run_check 2>&1 | tee -a logs/check.log
}

main "$@"
