#!/usr/bin/env bash

set -euo pipefail

log::header() {
	echo "=> $*"
}

log::indicator() {
	echo "-> $*"
}

log::exec_command() {
	log::indicator "$@"
	"$@"
}

log::fatal() {
	echo "FATAL: $*"
}

log::error() {
	echo "ERROR: $*"
}

log::warn() {
	echo "WARN: $*"
}

log::info() {
	echo "INFO: $*"
}

main() {
	####################################################################
	#                                                                  #
	#                             Setup                                #
	#                                                                  #
	####################################################################

	local scratch
	scratch="$(mktemp)"

	local -r check_log="${PWD}/logs/check.log"
	local -r execution_log="${PWD}/logs/execution.log"

	mkdir -p "$(dirname "${check_log}")"
	mkdir -p "$(dirname "${execution_log}")"

	touch logs/check.log

	git config --global advice.detachedHead false

	####################################################################
	#                                                                  #
	#                         Preflight Check                          #
	#                                                                  #
	####################################################################

	log::header 'Preflight check'

	if [ -z "${TEAMCI_CHECK_IMAGE:-}" ]; then
		log::fatal "Internal error. TEAMCI_CHECK_IMAGE missing. Please contact support."
		return 1
	fi

	####################################################################
	#                                                                  #
	#                         Set Constants                            #
	#                                                                  #
	####################################################################

	log::header 'Preparing environment' | tee -a "${check_log}"
	log::indicator 'Loading git metadata' | tee -a "${check_log}"

	local repo head_sha head_branch

	repo="$(buildkite-agent meta-data get teamci.repo.slug)"
	head_sha="$(buildkite-agent meta-data get teamci.head_sha)"
	head_branch="$(buildkite-agent meta-data get teamci.head_branch)"

	if [ -z "${repo}" ] || [ -z "${head_sha}" ] || [ -z "${head_branch}" ]; then
		log::fatal "Internal error. Missing repo/sha/branch metadata. Please contact support." | tee -a "${check_log}"
		return 1
	fi

	local -r CODE_DIR="${TEAMCI_CODE_DIR}/${repo}"

	local config_repo config_branch clone_status

	# config_repo="$(buildkite-agent meta-data get teamci.config.repo)"
	# config_branch="$(buildkite-agent meta-data get teamci.config.branch)"
	config_repo="$(echo "${repo}" | cut -d '/' -f 1)/teamci"
	config_branch=master

	local -r CONFIG_DIR="${TEAMCI_CODE_DIR}/${config_repo}"

	log::indicator 'Fetching access token' | tee -a "${check_log}"

	access_token_url="$(buildkite-agent meta-data get teamci.access_token_url)"

	if log::exec_command curl --show-error -o "${scratch}" --fail -H 'Accept: application/json' "${access_token_url}" 2>&1 | tee -a "${check_log}"; then
		log::info 'retrieved git access token'
		export "ACCESS_TOKEN=$(jq -re '.token' "${scratch}")"
	else
		log::fatal 'Could not fetch an access token. This is an internal error. You may attempt a retry. Contact support if the problem persists.'
		return 1
	fi

	####################################################################
	#                                                                  #
	#                         Clone Config                             #
	#                                                                  #
	####################################################################

	log::header "Cloning ${config_repo}" | tee -a "${check_log}"

	if [ -d "${CONFIG_DIR}/.git" ]; then
		pushd "${CONFIG_DIR}" > /dev/null

		log::exec_command git remote set-url origin "https://x-access-token:${ACCESS_TOKEN}@github.com/${config_repo}.git"
		log::exec_command git fetch -v --prune origin "${config_branch}"
		log::exec_command git checkout -f "${config_branch}"
		log::exec_command git pull origin "${config_branch}"

		popd > /dev/null
	else
		mkdir -p "${CODE_DIR}"

		set +e
		log::exec_command git clone -v "https://x-access-token:${ACCESS_TOKEN}@github.com/${config_repo}.git" "${CONFIG_DIR}"
		clone_status=$?
		set -e

		if [ $clone_status -ne 0 ]; then
			log::warn "Could not clone ${config_repo}. Using default config."
		else
			pushd "${CONFIG_DIR}" > /dev/null

			log::exec_command git fetch -v --prune origin "${config_branch}"
			log::exec_command git checkout -f "${config_branch}"

			popd > /dev/null
		fi
	fi

	####################################################################
	#                                                                  #
	#                         Clone Code                               #
	#                                                                  #
	####################################################################

	log::header "Cloning ${repo}" | tee -a "${check_log}"

	if [ -d "${CODE_DIR}/.git" ]; then
		pushd "${CODE_DIR}" > /dev/null

		log::exec_command git remote set-url origin "https://x-access-token:${ACCESS_TOKEN}@github.com/${repo}.git" 2>&1 | tee -a "${check_log}"
	else
		mkdir -p "${CODE_DIR}"

		log::exec_command git clone -v "https://x-access-token:${ACCESS_TOKEN}@github.com/${repo}.git" "${CODE_DIR}" 2>&1 | tee -a "${check_log}"

		pushd "${CODE_DIR}" > /dev/null
	fi

	if git fetch -v --prune origin "${head_branch}" && git checkout -f "${head_sha}"; then
		log::exec_command git clean -fdx 2>&1 | tee -a "${check_log}"
		popd > /dev/null
	else
		log::warn "Could not sync code. Was the branch deleted upstream? Skipping check." | tee -a "${check_log}"
		return 7
	fi

	####################################################################
	#                                                                  #
	#                       Prepare Check                              #
	#                                                                  #
	####################################################################

	echo "=> Pulling image" | tee -a "${check_log}"
	log::exec_command docker pull "${TEAMCI_CHECK_IMAGE}"  2>&1 | tee -a "${check_log}"

	local output_format

	output_format="$(docker inspect -f '{{ index .Config.Labels "com.teamci.output" }}' "${TEAMCI_CHECK_IMAGE}")"

	if [ -n "${output_format:-}" ]; then
		buildkite-agent meta-data set "teamci.output.${TEAMCI_CHECK_NAME}" "${output_format}"
	else
		buildkite-agent meta-data set "teamci.output.${TEAMCI_CHECK_NAME}" 'plain'
	fi

	####################################################################
	#                                                                  #
	#                       Execute \o/ \o/                            #
	#                                                                  #
	####################################################################

	log::header "Executing check" | tee -a "${check_log}"

	local check_exit_code

	set +e
	log::exec_command docker run --rm \
		-v "${CODE_DIR}:/data/code" \
		-v "${CONFIG_DIR}:/data/config" \
		-v "${PWD}/logs/tap.log:/data/logs/tap.log" \
		--cpus 1 \
		--memory 512m \
		"${TEAMCI_CHECK_IMAGE}" 2>&1 | tee -a "${execution_log}" | tee -a "${check_log}"
	check_exit_code=$?
	set -e

	return "${check_exit_code}"
}

main "$@"
