#!/usr/bin/env bash

set -euo pipefail

generate_pipeline() {
	echo 'env:'
	echo '  BUILDKITE_TIMEOUT: 15'
	echo 'steps:'
	for check in "$@"; do
		echo "  - label: ${check}"
		echo "    command: script/${check}"
	done
}

main() {
	source .buildkite/hooks/pre-check

	local scratch

	scratch="$(mktemp)"

	if ! buildkite-agent meta-data get 'teamci.pipeline_url' > /dev/null; then
		echo 'FATAL: could load pipeline configuration. Please contact support'
		return 1
	fi

	echo '~~~ :pipeline: Fetching'

	curl \
		-H 'Accept: application/json' \
		--fail \
		--silent \
		--show-error \
		--retry 3 \
		--retry-delay 30 \
		"$(buildkite-agent meta-data get 'teamci.pipeline_url')" \
		| tee "${scratch}"

	# Insert a newline after the HTTP body
	echo

	echo '~~~ :pipeline: Uploading'

	.buildkite/generate-pipeline < "${scratch}" | buildkite-agent pipeline upload
}

main "$@"
