#!/usr/bin/env bash

set -euo pipefail

main() {
	local teamci_pipeline buildkite_pipeline

	teamci_pipeline="$(mktemp)"
	buildkite_pipeline="$(mktemp)"

	if ! buildkite-agent meta-data get 'teamci.pipeline_url' > /dev/null; then
		echo 'FATAL: could load pipeline configuration. Please contact support'
		return 1
	fi

	echo '~~~ :pipeline: Fetching'

	curl \
		-H 'Accept: application/json' \
		--fail \
		--silent \
		--show-error \
		--retry 3 \
		--retry-delay 30 \
		"$(buildkite-agent meta-data get 'teamci.pipeline_url')" \
		| tee "${teamci_pipeline}"

	# Insert a newline after the HTTP body
	echo

	echo '~~~ :pipeline: Generating'

	.buildkite/generate-pipeline < "${teamci_pipeline}" | tee "${buildkite_pipeline}"

	echo '~~~ :pipeline: Uploading'

	buildkite-agent pipeline upload "${buildkite_pipeline}"
}

main "$@"
