#!/usr/bin/env bash

set -euo pipefail

main() {
	local scratch output exit_code
	scratch="$(mktemp)"
	output="$(mktemp)"

	cat > "${scratch}" # All files now saved in a file

	set +e
	xargs shellcheck -f json < "${scratch}" > "${output}"
	exit_code=$?
	set -e

	tapify.rb "${scratch}" < "${output}"

	if [ "${exit_code}" -eq 0 ]; then
		return 0
	else
		return 1
	fi
}

main "$@"
