#!/usr/bin/env bash

set -euo pipefail

main() {
	local output exit_code

	local config_file=/config/gometalinter/config.json
	local -a gometalinter_args=(--json --skip vendor)

	echo '~~~ Software versions'
	echo '$ gometalinter --version'
	gometalinter --version

	output="$(mktemp)"

	echo '~~~ Checking configuration'

	if [ ! -f "${config_file}" ]; then
		echo 'INFO: no configuration file. Using defaults'.
	else
		echo 'INFO: found configuration file'
		gometalinter_args+=(--config "${config_file}")
	fi

	echo '~~~ Running gometalinter'
	set +e
	gometalinter "${gometalinter_args[@]}" ./... > "${output}"
	exit_code=$?
	set -e

	if [ "${exit_code}" -ne 0 ]; then
		tapify.rb < "${output}"
		return 1
	else
		return 0
	fi
}

main "$@"
