#!/usr/bin/env bash

set -euo pipefail

declare scratch

echo '~~~ Generating file list'
scratch="$(mktemp)"

pushd "${CODE_DIR}" > /dev/null
git ls-files > "${scratch}"
popd > /dev/null

echo '~~~ Testing coverage'
docker-compose run \
	--rm \
	-v "${CODE_DIR}:/code" \
	-w /code \
	editorconfig < "${scratch}"
