#!/usr/bin/env bash

set -euo pipefail

buildkite-agent meta-data set "teamci.${BUILDKITE_LABEL}.title" 'eslint - Javascript/JSON linting'

echo '~~~ Software versions'

echo '$ eslint --version'
docker-compose run --rm eslint eslint --version

docker-compose run \
	--rm \
	-v "${CODE_DIR}:/code" \
	-v "${CONFIG_DIR}:/config" \
	-w "/code" \
	eslint
