#!/usr/bin/env bash

set -euo pipefail

declare scratch
scratch="$(mktemp)"

echo '~~~ Preparing options'

pushd "${CODE_DIR}" > /dev/null

if [ -x ".teamci/syntax/ls-files" ]; then
	echo 'INFO: Using file list from .teamci/syntax/ls-files'
	.teamci/syntax/ls-files > "${scratch}"
else
	echo 'INFO: Using file list from git ls-files'
	git ls-files > "${scratch}"
fi

popd > /dev/null

echo '~~~ Running Syntax Test'
docker-compose run --rm -v "${CODE_DIR}:/code" -w "/code" syntax < "${scratch}"
