#!/usr/bin/env bash

set -euo pipefail

if [ "${BUILDKITE_LABEL}" != ":pipeline:" ]; then
	echo '~~~ Building :docker:'

	docker-compose build syntax rubocop

	echo '~~~ Preparing TeamCI environment :house_with_garden:'

	export TEAMCI_CODE_DIR="${HOME}/teamci/check_runs"
fi
